services:
  - type: web
    name: jackers-solo
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
